spring.datasource.url=jdbc:mysql://localhost:3306/hospital
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=aHR0cHM6Ly93d3cuJ9ldmVzZS5jb20vd2F0Y2g/djlKUXc8dz1XZ1hjUQo
jwt.expiration=3600000